name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Deploy to EB
        run: |
          aws elasticbeanstalk create-application-version --application-name YOUR_APP_NAME --version-label v1 --source-bundle S3Bucket=YOUR_BUCKET_NAME,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --environment-name YOUR_ENV_NAME --version-label v1
